import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import fs from 'fs';
import path from 'path';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If you need to use async data fetching, do it in a page or a server component
export default async function RootLayout({ children }) {
  const folderNames = await getFolderNames();
  
  return (
    <html lang="en">
      <body className={inter.className}>

      <Link href="/">
            <button
              type="button"
              className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
            >
              Home
            </button>
          </Link>
        {folderNames.map((item) => (
          <Link key={item} href={`/${item}`}>
            <button
              type="button"
              className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
            >
              {item}
            </button>
          </Link>
        ))}

        {children}
      </body>
    </html>
  );
}

async function getFolderNames() {
  const dirPath = path.join(process.cwd(), 'app');
  let folderNames = [];
  try {
    const files = await fs.promises.readdir(dirPath, { withFileTypes: true });

    folderNames = files
      .filter(file => file.isDirectory())
      .map(file => file.name);
  } catch (error) {
    console.error('Error reading directory:', error);
  }
  
  return folderNames;
}
